stages:
  - publish
  - deliver

mirror:
  stage: publish
  script:
    - setsid ./ci/mirror.sh
  only:
    - /^(master.*)$/
  tags:
    - mirror

api_arm:
  stage: deliver
  script:
    - setsid ./ci/docker-deliver.sh "hue-monitoring" "1.0"
  only:
    refs:
      - /^(master.*)$/
    changes:
      - .gitlab-ci.yml
      - api/*
      - ci/docker-deliver.sh
      - docker-compose-build-arm.yml
      - Dockerfile.arm
  tags:
    - buildarm
