version: "3.3"

services: 
  hue-monitoring:
    image: comworkio/hue-monitoring:latest
    container_name: hue-monitoring
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    ports: 
      - 8080:8080
