version: "3.3"

services: 
  hue-monitoring:
    image: comworkio/hue-monitoring:latest-arm
    container_name: hue-monitoring
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.arm
      target: api
    env_file: 
      - .env
    ports: 
      - 8080:8080
